### ISSUE TITLE
Can't load local file .cram/.crai, need to change to Ander's local file proxy code

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#341] opened 2019-07-12 15:23 UTC
See #142 comments from

**Comment by AlistairNWard** [comment] 2019-07-12 15:30
How do you anticipate me contributing?!

**Comment by anderspitman** [comment] 2019-07-12 18:13
This is something we need to do anyway as we transition to the new backend. @fgvieira I think we should have this working relatively soon.

**Comment by anderspitman** [comment] 2020-03-13 18:11
@tonydisera this is working right? Obviously cram is working on gru, but are there any other subtle items attached to this that you remember?

**Comment by mvelinder** [comment] 2021-08-04 15:19
Need to clarify this is working for the paper release

**Comment by AlistairNWard** [comment] 2021-08-04 15:22
Duplicate of #597

**Closed by AlistairNWard** 2021-08-04 15:22 UTC
